# Operaciones Matemáticas y Estadística

In [2]:
import numpy as np

## Operaciones entre arrays y escalares

- Las operaciones entre arrays y escalares se hacen término a término

In [3]:
array = np.array([[1, 2, 3], [4, 5, 6]])
array

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
array * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [5]:
array - 1

array([[0, 1, 2],
       [3, 4, 5]])

In [6]:
1 / array 

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [7]:
array**2

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

## Operaciones de broadcasting entre arrays

- Los arrays tienen que tener la misma longitud al menos en una de sus dimensiones
- Pueden operar siempre que sean compatibles con el broadcasting:
    - El rango de ambos es el mismo
    - El tamaño en cada dimensión o es igual, o es 1 para cada uno de ellos
<center>
<img src="imgs/np_4.png"  alt="drawing" width="70%"/>
</center>

- El (3,) en broadcasting se interpreta como (3,1), y el número 5 se interpreta con dimensiones (1,1)
- Las dimensiones cumplen la condición de que tienen una dimensión que es 1

In [3]:
np.arange(3).shape

(3,)

In [5]:
np.arange(3) + 5

array([5, 6, 7])

- Aquí se cumple la condición de que ambos tienen una dimensión que es 1, tenemos (3,1) y (1,3)
    - Lo que hace que tengamos de dimensiones (3,3)

In [9]:
np.arange(3).reshape(1,3) + np.arange(3).reshape(3,1)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

- Esto se puede cumplir de multiples formas, aquí otro ejemplo

In [11]:
np.arange(27).reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [12]:
np.arange(3).reshape(3,1)

array([[0],
       [1],
       [2]])

In [10]:
np.arange(27).reshape(3,3,3) + np.arange(3).reshape(3,1)

array([[[ 0,  1,  2],
        [ 4,  5,  6],
        [ 8,  9, 10]],

       [[ 9, 10, 11],
        [13, 14, 15],
        [17, 18, 19]],

       [[18, 19, 20],
        [22, 23, 24],
        [26, 27, 28]]])

## Operaciones matemáticas con arrays

- Vamos a probar distintos tipos de funciones, así como operaciones entre arrays
- Las operaciones entre arrays deben de cumplir las condiciones de broadcasting
- Se pueden ver todas las funciones disponibles [aquí](https://numpy.org/doc/stable/reference/routines.math.html)
- Las más usadas son:

|Función|Descripcción|
|----|---|
|`abs, fabs`| Valor absoluto.|
|`sqrt`| Raíz cuadrada (equivalente a array \*\* 0.5).|
|`square`| Potencia al cuadrado (equivalente a array ** 2).|
|`exp`| Potencia de e.|
|`log, log10, log2, log1p`| Logaritmos en distintas bases.|
|`ceil`| Techo.|
|`floor`| Suelo.|
|`rint`| Redondeo al entero más cercano.|
|`modf`| Devuelve dos arrays uno con la parte fraccionaria y otro con la parte entera.|
|`isnan`| Devuelve un array booleano indicando si el valor es NaN o no.|
|`isfinite, isinf`| Devuelve un array booleano indicando si el valor es finito o no.|
|`cos, cosh, sin, sinh, tan, tanh`| Funciones trigonométricas.|
|`arccos, arccosh, arcsin, arcsinh, arctan, arctanh`| Funciones trigonométricas inversas.|
|`logical_not`| Inverso booleano de todos los valores del array (equivalente a -(array)).|

In [15]:
array_1 = np.arange(6)
array_2 = np.arange(6,12)
print(array_1)
print(array_2)

[0 1 2 3 4 5]
[ 6  7  8  9 10 11]


In [16]:
array_1 + array_2

array([ 6,  8, 10, 12, 14, 16])

In [17]:
array_1 * array_2

array([ 0,  7, 16, 27, 40, 55])

In [18]:
array_1 ** array_2

array([       0,        1,      256,    19683,  1048576, 48828125],
      dtype=int32)

- Ahora vamos a ver distintas funciones, que son muy utilizadas

In [20]:
array_1 = np.arange(6)**2
array_1

array([ 0,  1,  4,  9, 16, 25], dtype=int32)

In [21]:
np.sqrt(array_1)

array([0., 1., 2., 3., 4., 5.])

In [29]:
array_2 = np.linspace(0, 2*np.pi, 5)
array_2

array([0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531])

In [30]:
np.sin(array_2)

array([ 0.0000000e+00,  1.0000000e+00,  1.2246468e-16, -1.0000000e+00,
       -2.4492936e-16])

## Funciones incorporadas en arrays

- Los arrays llevan incorporadas funciones (métodos) tanto matemáticas como estadísticas.
- Todos los métodos de los arrays se pueden consultar [aquí](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html)

|Función|Descripcción|
|----|---|
|`sum`| Suma de elementos.|
|`mean`| Media aritmética de los elementos.|
|`median`| Mediana de los elementos.|
|`std`| Desviación estándar de los elementos.|
|`var`| Varianza de los elementos.|
|`min`| Valor mínimo de los elementos.|
|`max`| Valor máximo de los elementos.|
|`argmin`| Índice del valor mínimo.|
|`argmax`| Índice del valor máximo.|
|`cumsum`| Suma acumulada de los elementos.|
|`cumprod`| Producto acumulado de los elementos.|


In [32]:
array_1 = np.arange(6)
array_1

array([0, 1, 2, 3, 4, 5])

In [34]:
array_1.sum()

15

In [35]:
array_1.min()

0

In [36]:
array_1.max()

5

In [37]:
array_1.mean()

2.5

___
## Ejercicios

**1** Crea un array con los numeros del 0 al 100:
    - crea una variable con los anteriores valores en forma de matriz 10x10
    - multiplica el primer vector término a término por 5
    - saca la media y la desviación estándar del primer vector

**2** Genera un array aleatorio de 100 posiciones y muestra los cuantiles 95 y 5

**3**  Crea una función que sume el valor absoluto de todos los elementos negativos de una matriz recibida como parámetro. O devuelva "No hay negativos" en caso de que no los haya.