# Operaciones algebraicas

In [1]:
import numpy as np

- Toda la descripción del algebra lineal que podemos realizar con numpy la puedes encontrar [aquí](https://numpy.org/doc/stable/reference/routines.linalg.html)
- Nosotros vamos a ver las características más utilizadas

## Transposición de matrices

- La transposición nos sirve para girar una matriz:
    - Es decir si tenemos una matriz con dimensiones (3,2) al transponerla tendremos una (2,3)
    - Lo que hacemos es cambiar filas por columnas

<center>
<img src="imgs/np_5.png"  alt="drawing" width="50%"/>
</center>

In [3]:
A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [4]:
A.T

array([[1, 3],
       [2, 4]])

In [5]:
B = np.array([[1, 2, 3], [4, 5, 6]])
B.shape

(2, 3)

In [6]:
B.T.shape

(3, 2)

## Multiplicación matricial

- La multiplicacion matricial se puede realizar de distintos modos con el operador @,con np.matmul(), y con array.dot(anotherarray)

In [7]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

$\begin{bmatrix}
1 &2 \\ 
 3& 4
\end{bmatrix}\times
\begin{bmatrix}
5 &6 \\ 
 7& 8
\end{bmatrix} = 
\begin{bmatrix}
(1\cdot 5+2\cdot 7)&(1\cdot 6+2\cdot 8) \\ 
(3\cdot 5+4\cdot 7)&(3\cdot 6+4\cdot 8)
\end{bmatrix} = 
\begin{bmatrix}
19 &22 \\ 
 43& 50
\end{bmatrix}$

In [8]:
A @ B

array([[19, 22],
       [43, 50]])

In [9]:
A.dot(B)

array([[19, 22],
       [43, 50]])

In [10]:
np.matmul(A, B)

array([[19, 22],
       [43, 50]])

In [11]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])

- Se puede utilizar también para el producto de dos vectores

In [12]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [13]:
a @ b

70

In [14]:
np.dot(a, b)

70

- También podemos usarlo para multiplicar un vector por una matriz

In [15]:
A = np.array([[1, 2], [3, 4]])
b = np.array([5, 6])

Hay que tener en cuenta que el resultado de multiplicar matricialmente A@b es distinto a multiplicar b@A, esto es válido para todas las multiplicaciones matriciales

In [16]:
A @ b

array([17, 39])

La operación sería la siguiente
$\begin{bmatrix}
1 &2 \\ 
 3&4 
\end{bmatrix}\times \begin{bmatrix}
5 \\6 
\end{bmatrix}= \begin{bmatrix}
1\cdot 5 + 2 \cdot 6\\ 
3\cdot 5 + 4 \cdot 6
\end{bmatrix}= \begin{bmatrix}
17\\ 
39
\end{bmatrix}$

In [17]:
b @ A

array([23, 34])

La operación sería la siguiente
$\begin{bmatrix}
5 &6 
\end{bmatrix}\times \begin{bmatrix}
1 &2 \\ 
 3&4 
\end{bmatrix}= \begin{bmatrix}
(5\cdot 1 + 6 \cdot 3)& 
(5\cdot 2 + 6 \cdot 4)
\end{bmatrix}= \begin{bmatrix}
23& 
34
\end{bmatrix}$