# Funciones

In [1]:
import numpy as np

- En numpy existen distintos tipos de funciones de funciones, aquí vamos a ver las que consideramos más relevantes

## Tratamiento de arrays

|Función|Descripcción|
|----|---|
|`unique`| Calcula el conjunto único de elementos sin duplicados.|
|`intersect1d`| Calcula la intersección de los elementos de dos arrays.|
|`union1d`| Calcula la unión de los elementos de dos arrays.|
|`in1d`| Calcula un array booleano que indica si cada elemento del primer array está contenido en el segundo.|
|`setdiff1d`| Calcula la diferencia entre ambos conjuntos.|
|`setxor1d`| Calcula la diferencia simétrica entre ambos conjuntos.|

- La función unique es de las más usadas a la hora de hacer análisis sobre conjuntos de datos

In [2]:
coches_array = np.array(['Ford', 'Volvo', 'BMW','Ford','Nissan','BMW','Seat'])
np.unique(coches_array)

array(['BMW', 'Ford', 'Nissan', 'Seat', 'Volvo'], dtype='<U6')

In [3]:
np.unique(coches_array, return_counts=True)

(array(['BMW', 'Ford', 'Nissan', 'Seat', 'Volvo'], dtype='<U6'),
 array([2, 2, 1, 1, 1], dtype=int64))

También es válida para números, en general para cualquier dato compatible con arrays

In [5]:
numeros_array = np.array([1,3,5,4,5,7,4,9,0])
np.unique(numeros_array, return_counts=True)

(array([0, 1, 3, 4, 5, 7, 9]), array([1, 1, 1, 2, 2, 1, 1], dtype=int64))

## Guardado de arrays

|Función|Descripcción|
|----|---|
|`save`| Guarda un array en un archivo binario de numpy con extensión .npy|
|`savez`| Guarda multiples arrays en un archivo binario de numpy con extensión .npz|
|`savetxt`| Guarda un array en un archivo .txt|
|`load`| Carga los archivos guardados en .npy .npz o pickle|
|`loadtxt`| Carga los archivos guardados en .txt|


In [6]:
x = np.arange(10)
y = np.sin(x)

In [9]:
np.save('out.npy', x)

In [8]:
np.savez('out.npz', x=x, y=y) # Guarda los datos en un fichero .npz si indicamos x=x y=y, se guardan con el nombre x e y

In [10]:
np.savetxt('out.txt', x, delimiter=',') # Guarda los datos en un fichero .txt

Ahora los cargamos para ver los datos

In [11]:
np.load('out.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
print(np.load('out.npz')['x'])
print(np.load('out.npz')['y'])

[0 1 2 3 4 5 6 7 8 9]
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]


In [15]:
np.loadtxt('out.txt', delimiter=',')

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

## Funciones financieras

- Una descripción detallada de las funciones se puede ver [aquí](https://numpy.org/doc/1.17/reference/routines.financial.html)

|Función|Descripcción|
|----|---|
|`fv(rate, nper, pmt, pv[, when])`|Calcula el valor futuro.|
|`pv(rate, nper, pmt,[fv, when])`|Calcula el valor presente.|
|`npv(rate, values)`|VAN NPV (Net Present Value) de una serie de flujo de cajas.|
|`pmt(rate, nper, pv[, fv, when])`|Calcula el pago total, principal y intéres.|
|`ppmt(rate, per, nper, pv[, fv, when])`|Calcula el pago contra el principal.|
|`ipmt(rate, per, nper, pv[, fv, when])`|Calcula la proporción del interés del pago.|
|`irr(values)`|TIR: Internal Rate of Return (IRR).|
|`mirr(values, finance_rate, reinvest_rate)`| Internal Rate of Return (IRR) Modificada.|
|`nper(rate, pmt, pv[, fv, when])`|Calcula el número de pagos periodicos|
|`rate(nper, pmt, pv, fv[, when, guess, tol, …])`|Calcula la tasa de interes por periodo.|


- Vamos a hacer un ejemplo:
    - Teniendo que pagar cuotas de 25.000 € anuales
    - A 20 años
    - Y un tipo de interés del 2% anual
    - ¿Cual será su valor futuro?

In [18]:
np.fv(rate = 0.02, nper = 20, pmt = 25000, pv = 0) 

C:\Users\adriy\AppData\Local\Temp\ipykernel_36572\1813925726.py:1: DeprecationWarning: In accordance with NEP 32, the function fv was removed from NumPy version 1.20.  A replacement for this function is available in the numpy_financial library: https://pypi.org/project/numpy-financial
  np.fv(rate = 0.02, nper = 20, pmt = 25000, pv = 0)


RuntimeError: In accordance with NEP 32, the function fv was removed from NumPy version 1.20.  A replacement for this function is available in the numpy_financial library: https://pypi.org/project/numpy-financial

- Como vemos estas funciones han sido movidas de numpy a numpy_financial

In [17]:
!pip install numpy_financial

In [19]:
import numpy_financial as npf

In [20]:
npf.fv(rate = 0.02, nper = 20, pmt = 25000, pv = 0) 

-607434.2449729437

**Otros ejemplos**

- Cuál es el valor futuro después de 10 años de :
    - ahorrar 100€ ahora
    - más 100€ al mes 
    - asumiendo un retorno anual del 5%

In [22]:
npf.fv(0.05/12, 10*12, -100, -100)

15692.928894335748

In [23]:
100*10*12+100

12100

podemos hacer lo mismos para distintos retornos

In [25]:
a = np.array([0.02, 0.05, 0.07])/12

In [26]:
npf.fv(a, 10*12, -100, -100)

array([13394.08597514, 15692.92889434, 17509.44688102])

- Hipoteca a 20 años:
    - 2% anual
    - 10000 de entrada
    - pagos mensuales de 450€

In [27]:
npf.fv(0.02/12, 20*12, 450, 10000)

-147571.8560345149

___
# Ejercicios

**1.-** Crea un array y guardalo

**2.-** Lee el array y obten sus elementos únicos